language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.maven'

script: "./mvnw clean package -Dmaven.test.skip=true"

before_deploy:
  - zip -r kobobook-webservice-admin *
  - mkdir -p deploy/admin
  - mv kobobook-webservice-admin.zip deploy/admin/kobobook-webservice-admin.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kobobook-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: khj2872/Bookshop_admin
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kobobook-deploy
    key: admin/kobobook-webservice-admin.zip # S3 버킷에 저장된 kobobook-webservice-admin.zip 파일을 EC2로 배포
    bundle_type: zip
    application: kobobook-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: kobobook-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: khj2872/Bookshop_admin
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hykang2872@gmail.com